source 'https://rubygems.org'

gem 'hologram', git: 'https://github.com/pmeskers/hologram.git', branch: 'jsx-templates'
gem 'haml'
gem 'sass'
gem 'compass', '~> 1.0.1'
gem 'pry'
gem 'rspec'
gem 'capybara'
gem 'selenium-webdriver'
